### PR TITLE
Feature fund lookup

### PR DESCRIPTION
**Pull request by jbaxleyiii**
@delianides this will make it easy to lookup funds going forward with F1. We will need to set the env F1APIKEY on heroku.

The command is `@apollos lookup fund <fundname to search>`

Can you verify and merge this in for me? Thanks!

### CODE REVIEW

**Comment by delianides** [comment]
LGTM, but you should apply the ENV settings to heroku config before we merge this in.

**Comment by jbaxleyiii** [comment]
@delianides I think I have access. If I do I'll add it!

**Comment by jbaxleyiii** [comment]
Added @delianides :+1:

**Comment by delianides** [comment]
@jbaxleyiii this broke hubot

```
2015-10-08T14:23:33.235866+00:00 app[web.1]: [Thu Oct 08 2015 14:23:33 GMT+0000 (UTC)] ERROR Unable to load /app/scripts/f1-lookup: SyntaxError: unmatched OUTDENT
2015-10-08T14:23:33.235875+00:00 app[web.1]:   at Lexer.exports.Lexer.Lexer.error (/app/node_modules/coffee-script/lib/coffee-script/lexer.js:778:14)
2015-10-08T14:23:33.235873+00:00 app[web.1]:   at exports.throwSyntaxError (/app/node_modules/coffee-script/lib/coffee-script/helpers.js:197:13)
2015-10-08T14:23:33.235877+00:00 app[web.1]:   at Lexer.exports.Lexer.Lexer.pair (/app/node_modules/coffee-script/lib/coffee-script/lexer.js:690:16)
2015-10-08T14:23:33.235878+00:00 app[web.1]:   at Lexer.exports.Lexer.Lexer.outdentToken (/app/node_modules/coffee-script/lib/coffee-script/lexer.js:378:16)
2015-10-08T14:23:33.235879+00:00 app[web.1]:   at Lexer.exports.Lexer.Lexer.lineToken (/app/node_modules/coffee-script/lib/coffee-script/lexer.js:356:14)
2015-10-08T14:23:33.235881+00:00 app[web.1]:   at Lexer.exports.Lexer.Lexer.tokenize (/app/node_modules/coffee-script/lib/coffee-script/lexer.js:30:100)
2015-10-08T14:23:33.235882+00:00 app[web.1]:   at exports.compile.compile (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:35:36)
2015-10-08T14:23:33.235885+00:00 app[web.1]:   at Module.load (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
2015-10-08T14:23:33.235883+00:00 app[web.1]:   at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:176:14)
2015-10-08T14:23:33.235887+00:00 app[web.1]:   at Function.Module._load (module.js:310:12)
2015-10-08T14:23:33.235888+00:00 app[web.1]:   at Module.require (module.js:365:17)
2015-10-08T14:23:33.235890+00:00 app[web.1]:   at require (module.js:384:17)
2015-10-08T14:23:33.235891+00:00 app[web.1]:   at Robot.loadFile (/app/node_modules/hubot/src/robot.coffee:337:9, <js>:215:20)
2015-10-08T14:23:33.235893+00:00 app[web.1]:   at Robot.load (/app/node_modules/hubot/src/robot.coffee:359:9, <js>:238:30)
2015-10-08T14:23:33.235894+00:00 app[web.1]:   at HipChat.loadScripts (/app/node_modules/hubot/bin/hubot:95:5, <js>:98:13)
2015-10-08T14:23:33.235895+00:00 app[web.1]:   at emitNone (events.js:67:13)
2015-10-08T14:23:33.235897+00:00 app[web.1]:   at HipChat.emit (events.js:166:7)
2015-10-08T14:23:33.235898+00:00 app[web.1]:   at Connector.<anonymous> (/app/node_modules/hubot-hipchat/src/hipchat.coffee:126:9, <js>:152:17)
2015-10-08T14:23:33.235899+00:00 app[web.1]:   at emitNone (events.js:72:20)
2015-10-08T14:23:33.235900+00:00 app[web.1]:   at Connector.emit (events.js:166:7)
2015-10-08T14:23:33.235903+00:00 app[web.1]:   at Connector.<anonymous> (/app/node_modules/hubot-hipchat/src/connector.coffee:122:7, <js>:109:16)
2015-10-08T14:23:33.235902+00:00 app[web.1]:   at /app/node_modules/hubot-hipchat/src/connector.coffee:413:7, <js>:358:22
2015-10-08T14:23:33.235904+00:00 app[web.1]:   at Connector.g (events.js:260:16)
2015-10-08T14:23:33.235905+00:00 app[web.1]:   at emitTwo (events.js:87:13)
2015-10-08T14:23:33.235907+00:00 app[web.1]:   at Connector.emit (events.js:172:7)
2015-10-08T14:23:33.235908+00:00 app[web.1]:   at Connector.onStanza (/app/node_modules/hubot-hipchat/src/connector.coffee:471:7, <js>:413:21)
2015-10-08T14:23:33.235909+00:00 app[web.1]:   at emitOne (events.js:77:13)
2015-10-08T14:23:33.235910+00:00 app[web.1]:   at Client.emit (events.js:169:7)
2015-10-08T14:23:33.235912+00:00 app[web.1]:   at Client.onStanza (/app/node_modules/node-xmpp-client/index.js:224:14)
2015-10-08T14:23:33.235913+00:00 app[web.1]:   at emitOne (events.js:77:13)
2015-10-08T14:23:33.235914+00:00 app[web.1]:   at Connection.emit (events.js:169:7)
2015-10-08T14:23:33.235915+00:00 app[web.1]:   at Connection.onStanza (/app/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:370:14)
2015-10-08T14:23:33.235917+00:00 app[web.1]:   at StreamParser.<anonymous> (/app/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:226:14)
2015-10-08T14:23:33.235918+00:00 app[web.1]:   at emitOne (events.js:77:13)
2015-10-08T14:23:33.235920+00:00 app[web.1]:   at StreamParser.emit (events.js:169:7)
2015-10-08T14:23:33.235921+00:00 app[web.1]:   at SaxLtx.<anonymous> (/app/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:59:22)
2015-10-08T14:23:33.235922+00:00 app[web.1]:   at emitOne (events.js:77:13)
2015-10-08T14:23:33.235923+00:00 app[web.1]:   at SaxLtx.emit (events.js:169:7)
2015-10-08T14:23:33.235925+00:00 app[web.1]:   at SaxLtx._handleTagOpening (/app/node_modules/ltx/lib/parsers/ltx.js:30:18)
2015-10-08T14:23:33.235926+00:00 app[web.1]:   at SaxLtx.write (/app/node_modules/ltx/lib/parsers/ltx.js:92:26)
2015-10-08T14:23:33.235927+00:00 app[web.1]:   at StreamParser.write (/app/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:128:21)
2015-10-08T14:23:33.235929+00:00 app[web.1]:   at Connection.onData (/app/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:306:21)
2015-10-08T14:23:33.235930+00:00 app[web.1]:   at emitOne (events.js:82:20)
```

**Comment by jbaxleyiii** [comment]
@delianides dangit! Sorry man! I'll fix it!

**Comment by jbaxleyiii** [comment]
@delianides fixed on the master branch

**Comment by delianides** [comment]
@jbaxleyiii FYI, pushing to master now triggers a build in heroku.

**Comment by jbaxleyiii** [comment]
@delianides I'm coming to hug you

**Pull request merged**
